### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [AMereBagatelle/AFKPeace#17] opened 2021-03-09 17:37 UTC
This is the only mod. Fabric loader 0.11.2.
crash report: https://gist.github.com/DragonEggBedrockBreaking/f11224f3262f570bc59276a98a66007a

**Comment by AMereBagatelle** [comment] 2021-03-09 18:03
Duplicate of #16

**Closed as completed by AMereBagatelle** 2021-03-09 18:03 UTC

**Comment by DragonEggBedrockBreaking** [comment] 2021-03-09 18:48
> Duplicate of #16

Oh, sorry.
